### ISSUE TITLE
Something broke in help.py

### ISSUE THREAD

**Issue by msqueentired** [stevenpitts/makubot#283]
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/help.py", line 848, in command_callback
    return await self.send_bot_help(mapping)
  File "/usr/src/app/src/help.py", line 81, in send_bot_help
    help_commands_text=get_help_commands_text(self.context.bot),
  File "/usr/src/app/src/help.py", line 42, in get_help_commands_text
    text += cmd_help_text(bot, cmd)
  File "/usr/src/app/src/help.py", line 34, in cmd_help_text
    help_brief = bot.all_commands[cmd].help.split('\n')[0]
AttributeError: 'NoneType' object has no attribute 'split'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'split'```

**Comment by msqueentired** [comment]
Looks like this was accidentally introduced in 570c2de718dd16c79eb80b359df94f480be5d13b.
